const themes = [
    "Vs-Dark",
    "Vs-Light",
    "Active4D",
    "All Hallows Eve",
    "Amy",
    "Birds of Paradise",
    "Blackboard",
    "Brilliance Black",
    "Brilliance Dull",
    "Clouds Midnight",
    "Cobalt",
    "Cobalt2",
    "Dominion Day",
    "Dracula",
    "Espresso Libre",
    "GitHub Dark",
    "GitHub Light",
    "IDLE",
    "idleFingers",
    "iPlastic",
    "Katzenmilch",
    "krTheme",
    "Kuroir Theme",
    "MagicWB (Amiga)",
    "Merbivore Soft",
    "Merbivore",
    "monoindustrial",
    "Monokai Bright",
    "Monokai",
    "Night Owl",
    "Nord",
    "Oceanic Next",
    "Pastels on Dark",
    "Slush and Poppies",
    "Solarized-dark",
    "Solarized-light",
    "SpaceCadet",
    "Sunburst",
    "themelist",
    "Tomorrow-Night-Blue",
    "Tomorrow-Night-Bright",
    "Tomorrow-Night-Eighties",
    "Tomorrow-Night",
    "Tomorrow",
    "Twilight",
    "Upstream Sunburst",
    "Vibrant Ink",
    "Zenburnesque"
];

export default themes